// Regenerates lib/api-zod/src/index.ts after every orval codegen run.
//
// Orval's "zod" client always writes its own barrel to
// lib/api-zod/src/index.ts that does:
//   export * from "./generated/api";
//   export * from "./generated/types";
// Any operation with BOTH a path parameter and query parameters gets a
// zod "<Op>Params" object (merged path params) in generated/api.ts AND a
// plain TS "<Op>Params" type (query params only) in generated/types/ —
// same name, different files, which TS reports as an ambiguous export
// (TS2308) when both are wildcard re-exported. Since this is regenerated
// on every codegen run, we cannot hand-edit the barrel once; instead this
// script re-derives it after orval runs, dropping only the type modules
// whose exported name collides with a value already exported from
// generated/api.ts.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const srcDir = path.resolve(fileURLToPath(import.meta.url), "..", "..", "src");
const apiFile = path.join(srcDir, "generated", "api.ts");
const typesDir = path.join(srcDir, "generated", "types");

const apiSource = readFileSync(apiFile, "utf8");
const apiNames = new Set(
  [...apiSource.matchAll(/^export const (\w+)/gm)].map((m) => m[1]),
);

const typeFiles = readdirSync(typesDir)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .sort();

const kept = [];
const skipped = [];
for (const file of typeFiles) {
  const source = readFileSync(path.join(typesDir, file), "utf8");
  const exported = [...source.matchAll(/^export type (\w+)/gm)].map((m) => m[1]);
  const collides = exported.some((name) => apiNames.has(name));
  const moduleName = file.replace(/\.ts$/, "");
  (collides ? skipped : kept).push(moduleName);
}

const lines = [
  'export * from "./generated/api";',
  "",
  '// NOTE: This file is regenerated by scripts/fix-barrel.mjs after every',
  '// `orval` run (see the "codegen" script) — do not hand-edit it, and do',
  '// not restore a plain `export * from "./generated/types"` line. See that',
  "// script for why the exclusions below are necessary.",
];

if (skipped.length > 0) {
  lines.push(`// Skipped (name collides with a value in "./generated/api"): ${skipped.join(", ")}`);
}

for (const moduleName of kept) {
  lines.push(`export * from "./generated/types/${moduleName}";`);
}

writeFileSync(path.join(srcDir, "index.ts"), lines.join("\n") + "\n");

console.log(
  `fix-barrel: re-exported ${kept.length} type module(s), skipped ${skipped.length} colliding module(s)${
    skipped.length > 0 ? ` (${skipped.join(", ")})` : ""
  }.`,
);
